apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend2-deployment
  namespace: my-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend2
  template:
    metadata:
      labels:
        app: backend2
    spec:
      containers:
        - name: backend2
          image: tjdanqkr/test:back2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: profiles
              value: prod
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: USERNAME
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: PASSWORD
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: create
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "500m"
              memory: "500Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: backend2-service
  namespace: my-namespace
spec:
  selector:
    app: backend2
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
