apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql1-pv
  labels:
    type: mysql1

spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /Users/qkrtjdan/Desktop/code/kube-test/mysql1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "mysql1-storage"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-b-1-pvc
  namespace: my-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.5Gi
  selector:
    matchLabels:
      type: mysql1
  storageClassName: "mysql1-storage"
