apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql2-pv
  labels:
    type: mysql2

spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /kube-test/mysql2
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "mysql2-storage"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-b-2-pvc
  namespace: my-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.5Gi
  selector:
    matchLabels:
      type: mysql2
  storageClassName: "mysql2-storage"
