apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
  labels:
    type: local

spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /Users/qkrtjdan/Desktop/code/kube-test/
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
