apiVersion: v1
kind: Service
metadata:
  name: {{ include "back1.fullname" . }}
  labels:
    {{- include "back1.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "back1.selectorLabels" . | nindent 4 }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name:  {{ include "back1.fullname" . }}
  labels:
    {{- include "back1.labels" . | nindent 4 }}
    release: pgs
spec:
  selector:
    matchLabels:
      app: {{- include "back1.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: "/actuator/prometheus"