apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "back2.fullname" . }}-config
  labels:
      {{- include "back2.labels" . | nindent 4 }}
data:
  logback.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
      <configuration>
      <appender name="LOKI" class="com.github.loki4j.logback.Loki4jAppender">
      <http>
      <url>http://loki.mon.svc.cluster.local:3100/loki/api/v1/push</url>
      </http>
      <format>
      <label>
      <pattern>app=${name},host=${HOSTNAME},level=%level</pattern>
      <readMarkers>true</readMarkers>
      </label>
      <message>
      <pattern>
      {
      "level":"%level",
      "class":"%logger{36}",
      "thread":"%thread",
    "message": "%message",
    "requestId": "%X{X-Request-ID}"
    }
      </pattern>
      </message>
      </format>
      </appender>

      <root level="INFO">
      <appender-ref ref="LOKI" />
      </root>
      </configuration>